apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs-join-dn2
  labels:
    type: ambari
    app: dn2
spec:
  serviceName: "datanode1"
  replicas: 1
  selector:
    matchLabels:
      type: ambari
      app: dn2
  templates:
    metadata:
      labels:
        type: ambari
        app: dn2
    spec:
      hostname: dn2
      subdomain: jts
      setHostnameAsFQDN: true
      containers:
      - image: docker.jointree.co.kr/jointree/joindatanode2full:v7.0
        name: dn2
        command: ["/bin/bash","-c","ambari-agent start && sleep infinity"]
        env:
        - name: JAVA_HOME
          value: "/usr/lib/jvm/java-1.8.0-openjdk/"
        securityContext:
        privileged: true
        ports:
        - name: sshd
          containerPort: 22
        - name: ambariport
          containerPort: 8080
      restartPolicy: Always
      imagePullSecrets:
      - name: docker-registry-login
      nodeSelector:
       kubernetes.io/hostname: "datanode2"