kind: Service
apiVersion: v1
metadata:
  name: base-svc-ambari
  labels:
    app: ambari
spec:
  ports:
    - name: service
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30101
    - name: hue
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30102
  selector:
    type: ambari
    app: server
  type: NodePort
