
kind: Service
apiVersion: v1
metadata:
  name: svc-spring
  labels:
    app: svc-spring
spec:
  ports:
    - name: spring
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31004
  selector:
    app: spring
    type: ambari
  type: NodePort
