dependencies:
- name: my-flask
  version: 2.1.6
  repository: https://docker.jointree.co.kr/chartrepo/jointree
  condition: zookeeper.enabled
- name: mysql
  version: 1.6.4
  repository: https://charts.helm.sh/stable
  condition: mysql.enabled
- name: postgresql
  version: 8.6.4
  repository: https://charts.helm.sh/stable
  condition: postgresql.enabled
