apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeus-web-front
  namespace: zeus-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeus-web
      type: zeus
  template:
    metadata:
      labels:
        app: zeus-web
        type: zeus
    spec:
      hostname: zeusfront
      subdomain: zeus
      setHostnameAsFQDN: true
      containers:
      - name: zeusfront
        image: docker.jointree.co.kr/jointree/testfront
        command: ["/bin/bash", "-c"]
        args: ["nginx ; sleep infinity"]
        ports:
        - containerPort: 4203
        volumeMounts:
        - name: zeus-git-front
          mountPath: /tmp
        imagePullPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: analysis1
      imagePullSecrets:
      - name: harbor-admin-login
      volumes:
      - name: zeus-git-front
        gitRepo:
         repository: https://github.com/eunsukcho/zeus.git
         revision: publish
