apiVersion: v1
kind: Service
metadata:
  name: zeus-service-web
  namespace: zeus-web
  labels:
    app: zeus-web
spec:
  selector:
    app: zeus-web
  type: NodePort
  ports:
  - port: 4203
    targetPort: 4203
    nodePort: 32103
    name : zeus-front
  - port: 3000
    targetPort: 3000
    nodePort : 32104 
    name : zeus-back