kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-jupyter-data
  labels:
    type: local
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/pv/jupyter/data" 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jupyter-data-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi 
