apiVersion: v1
kind: Pod
metadata:
  name: base-join-nn2
  labels:
    type: ambari
spec:
  hostname: nn2
  subdomain: jts
  setHostnameAsFQDN: true
  containers:
  - image: docker.jointree.co.kr/jointree/joinnamenode2full:v7.0
    name: nn2
    env:
    - name: JAVA_HOME
      value: "/usr/lib/jvm/java-1.8.0-openjdk/"
    envFrom:
     - configMapRef:
        name: server-cfg
    volumeMounts:
      - name: csv-conn
        mountPath: /csv
    securityContext:
     privileged: true
    ports:
    - name: sshd
      containerPort: 22
    - name: ambariport
      containerPort: 8080
  restartPolicy: Always
  imagePullSecrets:
   - name: harbor-admin-login
  nodeSelector:
   kubernetes.io/hostname: "namenode2"
  volumes:
    - name: csv-conn
      persistentVolumeClaim:
        claimName: pvc-csv-claim
