apiVersion: v1
kind: Pod
metadata:
  name: base-join-nn1
  labels:
    type: ambari
    app: server
spec:
  hostname: nn1
  subdomain: jts
  setHostnameAsFQDN: true
  containers:
  - image: docker.jointree.co.kr/jointree/joinnamenode1full:v7.0
    name: ambariserver
    env:
    - name: JAVA_HOME
      value: "/usr/lib/jvm/java-1.8.0-openjdk"
    volumeMounts:
      - name: csv-conn
        mountPath: /csv
    securityContext:
     privileged: true
    ports:
    - name: sshd
      containerPort: 22
    - name: ambariport
      containerPort: 8080
  restartPolicy: Always
  imagePullSecrets:
   - name: docker-registry-login
  volumes:
    - name: csv-conn
      persistentVolumeClaim:
        claimName: pvc-csv-claim
  nodeSelector:
   kubernetes.io/hostname: "namenode1"


apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/bash","-c","mkdir -p /csv  && sleep infinity"]
    volumeMounts:
    - name: csv-conn
      mountPath: /csv
  volumes:
  - name: csv-conn
    persistentVolumeClaim:
     claimName: csv-claim
  restartPolicy: Always
