kind: PersistentVolume
apiVersion: v1
metadata:
  name: broker-var-pv
  labels:
    type: local
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
   namespace: default
   name: docker-broker-var
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /druidpv/broker_var
