kind: PersistentVolume
apiVersion: v1
metadata:
  name: coordinator-var-pv
  labels:
    type: local
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
   namespacce: default
   name: docker-coordinator-var
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /druidpv/coordinator_var
