kind: PersistentVolume
apiVersion: v1
metadata:
  name: middle-var-pv
  labels:
    type: local
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
   namespace: default
   name: docker-middle-var
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /druidpv/middle_var
