kind: PersistentVolume
apiVersion: v1
metadata:
  name: metadata-pv
  labels:
    type: local
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
   namespacce: default
   name: docker-metadata-data
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /druidpv/metadata
