kind: PersistentVolume
apiVersion: v1
metadata:
  name: middlemanager-pv
  labels:
    type: local
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
   namespace: default
   name: middlemanager-claim0
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /druidpv/middlemanager
