apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeus-web-back
  namespace: zeus-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeus-web
  template:
    metadata:
      labels:
        app: zeus-web
    spec:
      hostname: zeusback
      subdomain: zeus
      setHostnameAsFQDN: true
      containers:
      - name: zeusback
        image: golang:latest
        command: ["/bin/bash", "-c", "cd /go/Zeus_Server/Zeus_Portal_Server && make dev && sleep infinity"]
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: zeus-git
          mountPath: /go/Zeus_Server
      nodeSelector:
        kubernetes.io/hostname: analysis1
      imagePullSecrets:
      - name: harbor-admin-login
      volumes:
      - name: zeus-git
        gitRepo:
         repository: https://github.com/eunsukcho/Zeus_Portal_Server.git
         revision: main