apiVersion: v1
kind: Service
metadata:
  name: zeus-service
  namespace: zeus-web
  labels:
    app: zeus-web
spec:
  selector:
    app: zeus-web
  type: NodePort
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 32101 
         name : zeus-front
    - port: 3000
      targetPort: 3000
      nodePort : 32104 
      name : zeus-back