apiVersion: v1
kind: Pod
metadata:
  name: base-join-nn1
  labels:
    app: ambari
    test: jts
spec:
  hostname: nn1
  subdomain: jts
  setHostnameAsFQDN: true
  containers:
  - image: docker.jointree.co.kr/jointree/joinambari:v7.0
    name: ambariserver
    command: ["/bin/bash","-c","ambari-server install-mpack --mpack=https://github.com/steven-matison/dfhz_hdp_mpack/raw/master/hdp-ambari-mpack-3.1.4.0.tar.gz --verbose"]
    env:
    - name: JAVA_HOME
      value: "/usr/lib/jvm/java-1.8.0-openjdk"
    envFrom:
     - configMapRef:
        name: server-cfg
    volumeMounts:
      - name: csv-conn
        mountPath: /csv
    securityContext:
     privileged: true
    ports:
    - name: sshd
      containerPort: 22
    - name: ambariport
      containerPort: 8080
  restartPolicy: Always
  imagePullSecrets:
   - name: docker-registry-login
  volumes:
    - name: csv-conn
      persistentVolumeClaim:
        claimName: csvconn
