apiVersion: v1
kind: Pod
metadata:
  name: test-join-nn1
  labels:
    app: testambari
    test: testjts
spec:
  hostname: nn1
  subdomain: jts
  setHostnameAsFQDN: true
  containers:
  - image: docker.jointree.co.kr/jointree/basenn1:v0.5
    name: ambariserver
    env:
    - name: JAVA_HOME
      value: "/usr/lib/jvm/java-1.8.0-openjdk"
    envFrom:
     - configMapRef:
        name: server-cfg
    volumeMounts:
      - name: csv-conn
        mountPath: /csv
    securityContext:
     privileged: true
    ports:
    - name: sshd
      containerPort: 22
    - name: ambariport
      containerPort: 8080
  restartPolicy: Always
  imagePullSecrets:
   - name: docker-registry-login
  volumes:
    - name: csv-conn
      persistentVolumeClaim:
        claimName: csvconn
