kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgres
  labels:
    app: postgres
spec:
  storageClassName: microk8s-hostpath
  capacity:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi