apiVersion: v1
kind: Service
metadata:
  name: svc-postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
    nodePort: 32201
  type: NodePort 
  selector:
    app: postgres