kind: Service
apiVersion: v1
metadata:
  name: svc-jupyter
  labels:
    app: svc-jupyter
spec:
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 32002
  selector:
    app: jupyter2
  type: NodePort